apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: {{ include "dlh.namespace" . }}
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
  labels: {{- include "dlh.labels" . | nindent 4 }}
data:
  default-v1: |
    s3:
      endpoint: dlh-minio.{{ include "dlh.namespace" . }}.svc.cluster.local:9000
      bucket: artifacts
      insecure: true
      accessKeySecret:
        name: minio-artifact-creds
        key: accesskey
      secretKeySecret:
        name: minio-artifact-creds
        key: secretkey
