package runs

import (
	"context"
	"fmt"
	"time"

	wfv1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
	wfclient "github.com/argoproj/argo-workflows/v3/pkg/client/clientset/versioned"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Submitter creates new Workflow CRs from WorkflowTemplate refs.
type Submitter struct {
	Argo      wfclient.Interface
	Namespace string
}

// SubmitRequest is the inbound payload (one-step removed from the HTTP DTO).
type SubmitRequest struct {
	ScenarioID string
	TargetID   string
	Parameters map[string]string
	CreatedBy  string // OIDC subject
}

// SubmitResult is what we return to the caller.
type SubmitResult struct {
	RunID     string
	TargetID  string
	StartedAt time.Time
}

// Submit creates the Workflow CR. RunID format is "<scenarioID>-YYYYMMDD-HHMMSS"
// (previously generated by run-scenario.sh, now by the controlplane API).
func (s *Submitter) Submit(ctx context.Context, req SubmitRequest) (*SubmitResult, error) {
	if req.ScenarioID == "" {
		return nil, fmt.Errorf("scenarioId is required")
	}
	// Verify the template exists; this becomes 404 to the API caller.
	if _, err := s.Argo.ArgoprojV1alpha1().WorkflowTemplates(s.Namespace).Get(ctx, req.ScenarioID, metav1.GetOptions{}); err != nil {
		if apierrors.IsNotFound(err) {
			return nil, fmt.Errorf("scenario %q not found: %w", req.ScenarioID, err)
		}
		return nil, fmt.Errorf("get workflowtemplate %q: %w", req.ScenarioID, err)
	}

	now := time.Now().UTC()
	runID := fmt.Sprintf("%s-%s", req.ScenarioID, now.Format("20060102-150405"))

	labels := map[string]string{
		"dlh.scenario": req.ScenarioID,
		"dlh.run-id":   runID,
	}
	if req.TargetID != "" {
		labels["dlh.target"] = req.TargetID
	}

	params := make([]wfv1.Parameter, 0, len(req.Parameters)+1)
	for k, v := range req.Parameters {
		val := wfv1.AnyString(v)
		params = append(params, wfv1.Parameter{Name: k, Value: &val})
	}
	// Always add target_id (empty for local); chaos WT http steps reference it.
	tidVal := wfv1.AnyString(req.TargetID)
	params = append(params, wfv1.Parameter{Name: "target_id", Value: &tidVal})

	wf := &wfv1.Workflow{
		ObjectMeta: metav1.ObjectMeta{
			Name:      runID,
			Namespace: s.Namespace,
			Labels:    labels,
			Annotations: map[string]string{
				"dlh.created-by": req.CreatedBy,
			},
		},
		Spec: wfv1.WorkflowSpec{
			WorkflowTemplateRef: &wfv1.WorkflowTemplateRef{Name: req.ScenarioID},
			Arguments:           wfv1.Arguments{Parameters: params},
		},
	}

	created, err := s.Argo.ArgoprojV1alpha1().Workflows(s.Namespace).Create(ctx, wf, metav1.CreateOptions{})
	if err != nil {
		return nil, fmt.Errorf("create workflow: %w", err)
	}
	return &SubmitResult{RunID: created.Name, TargetID: req.TargetID, StartedAt: created.CreationTimestamp.Time}, nil
}
