apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dlh-controlplane
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: dlh-test-fw
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dlh-test-fw
  source:
    repoURL: https://github.com/REPLACE-OWNER/dlh-test-fw.git
    targetRevision: main
    path: controlplane/deploy
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dlh-test-fw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
